<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('languages', function (Blueprint $table) {
            $table->id();
            $table->string('name', 64)->unique();
        });

        DB::insert(
            "INSERT INTO `languages` (`id`, `name`) VALUES
            (1, 'Abkhazian'),
            (2, 'Achinese'),
            (3, 'Acoli'),
            (4, 'Adangme'),
            (5, 'Adygei'),
            (6, 'Adyghe'),
            (7, 'Afar'),
            (8, 'Afrihili'),
            (9, 'Afrikaans'),
            (10, 'Afro-Asiatic languages'),
            (11, 'Ainu'),
            (12, 'Akan'),
            (13, 'Akkadian'),
            (14, 'Albanian'),
            (15, 'Alemannic'),
            (16, 'Aleut'),
            (17, 'Algonquian languages'),
            (18, 'Alsatian'),
            (19, 'Altaic languages'),
            (20, 'Amharic'),
            (21, 'Angika'),
            (22, 'Apache languages'),
            (23, 'Arabic'),
            (24, 'Arabic - Algeria'),
            (25, 'Arabic - Bahrain'),
            (26, 'Arabic - Egypt'),
            (27, 'Arabic - Iraq'),
            (28, 'Arabic - Jordan'),
            (29, 'Arabic - Kuwait'),
            (30, 'Arabic - Lebanon'),
            (31, 'Arabic - Libya'),
            (32, 'Arabic - Morocco'),
            (33, 'Arabic - Oman'),
            (34, 'Arabic - Qatar'),
            (35, 'Arabic - Saudi Arabia'),
            (36, 'Arabic - Syria'),
            (37, 'Arabic - Tunisia'),
            (38, 'Arabic - United Arab Emirates'),
            (39, 'Arabic - Yemen'),
            (40, 'Aragonese'),
            (41, 'Arapaho'),
            (42, 'Arawak'),
            (43, 'Armenian'),
            (44, 'Aromanian'),
            (45, 'Artificial languages'),
            (46, 'Arumanian'),
            (47, 'Assamese'),
            (48, 'Asturian'),
            (49, 'Asturleonese'),
            (50, 'Athapascan languages'),
            (51, 'Australian languages'),
            (52, 'Austronesian languages'),
            (53, 'Avaric'),
            (54, 'Avestan'),
            (55, 'Awadhi'),
            (56, 'Aymara'),
            (57, 'Azerbaijani'),
            (58, 'Azeri - Cyrillic'),
            (59, 'Azeri - Latin'),
            (60, 'Bable'),
            (61, 'Balinese'),
            (62, 'Baltic languages'),
            (63, 'Baluchi'),
            (64, 'Bambara'),
            (65, 'Bamileke languages'),
            (66, 'Banda languages'),
            (67, 'Bantu languages'),
            (68, 'Basa'),
            (69, 'Bashkir'),
            (70, 'Basque'),
            (71, 'Batak languages'),
            (72, 'Bedawiyet'),
            (73, 'Beja'),
            (74, 'Belarusian'),
            (75, 'Bemba'),
            (76, 'Bengali'),
            (77, 'Berber languages'),
            (78, 'Bhojpuri'),
            (79, 'Bihari languages'),
            (80, 'Bikol'),
            (81, 'Bilin'),
            (82, 'Bini'),
            (83, 'Bislama'),
            (84, 'Blin'),
            (85, 'Bliss'),
            (86, 'Blissymbolics'),
            (87, 'Blissymbols'),
            (88, 'Bokmål, Norwegian'),
            (89, 'Bosnian'),
            (90, 'Braj'),
            (91, 'Breton'),
            (92, 'Buginese'),
            (93, 'Bulgarian'),
            (94, 'Buriat'),
            (95, 'Burmese'),
            (96, 'Caddo'),
            (97, 'Castilian'),
            (98, 'Catalan'),
            (99, 'Caucasian languages'),
            (100, 'Cebuano'),
            (101, 'Celtic languages'),
            (102, 'Central American Indian languages'),
            (103, 'Central Khmer'),
            (104, 'Chagatai'),
            (105, 'Chamic languages'),
            (106, 'Chamorro'),
            (107, 'Chechen'),
            (108, 'Cherokee'),
            (109, 'Chewa'),
            (110, 'Cheyenne'),
            (111, 'Chibcha'),
            (112, 'Chichewa'),
            (113, 'Chinese'),
            (114, 'Chinese - China'),
            (115, 'Chinese - Hong Kong SAR'),
            (116, 'Chinese - Macau SAR'),
            (117, 'Chinese - Singapore'),
            (118, 'Chinese - Taiwan'),
            (119, 'Chinook jargon'),
            (120, 'Chipewyan'),
            (121, 'Choctaw'),
            (122, 'Chuang'),
            (123, 'Church Slavic'),
            (124, 'Church Slavonic'),
            (125, 'Chuukese'),
            (126, 'Chuvash'),
            (127, 'Classical Nepal Bhasa'),
            (128, 'Classical Newari'),
            (129, 'Classical Syriac'),
            (130, 'Cook Islands Maori'),
            (131, 'Coptic'),
            (132, 'Cornish'),
            (133, 'Corsican'),
            (134, 'Cree'),
            (135, 'Creek'),
            (136, 'Creoles and pidgins'),
            (137, 'Creoles and pidgins, English based'),
            (138, 'Creoles and pidgins, French-based'),
            (139, 'Creoles and pidgins, Portuguese-based'),
            (140, 'Crimean Tatar'),
            (141, 'Crimean Turkish'),
            (142, 'Croatian'),
            (143, 'Cushitic languages'),
            (144, 'Czech'),
            (145, 'Dakota'),
            (146, 'Danish'),
            (147, 'Dargwa'),
            (148, 'Delaware'),
            (149, 'Dene Suline'),
            (150, 'Dhivehi'),
            (151, 'Dimili'),
            (152, 'Dimli'),
            (153, 'Dinka'),
            (154, 'Divehi'),
            (155, 'Dogri'),
            (156, 'Dogrib'),
            (157, 'Dravidian languages'),
            (158, 'Duala'),
            (159, 'Dutch'),
            (160, 'Dutch - Belgium'),
            (161, 'Dutch - Netherlands'),
            (162, 'Dutch, Middle (ca.1050-1350)'),
            (163, 'Dyula'),
            (164, 'Dzongkha'),
            (165, 'Eastern Frisian'),
            (166, 'Edo'),
            (167, 'Efik'),
            (168, 'Egyptian (Ancient)'),
            (169, 'Ekajuk'),
            (170, 'Elamite'),
            (171, 'English'),
            (172, 'English - Australia'),
            (173, 'English - Belize'),
            (174, 'English - Canada'),
            (175, 'English - Caribbean'),
            (176, 'English - Great Britain'),
            (177, 'English - India'),
            (178, 'English - Ireland'),
            (179, 'English - Jamaica'),
            (180, 'English - New Zealand'),
            (181, 'English - Philippines'),
            (182, 'English - Southern Africa'),
            (183, 'English - Trinidad'),
            (184, 'English - United States'),
            (185, 'English - Zimbabwe'),
            (186, 'English, Middle (1100-1500)'),
            (187, 'English, Old (ca.450-1100)'),
            (188, 'Erzya'),
            (189, 'Esperanto'),
            (190, 'Estonian'),
            (191, 'Ewe'),
            (192, 'Ewondo'),
            (193, 'Fang'),
            (194, 'Fanti'),
            (195, 'Faroese'),
            (196, 'Farsi - Persian'),
            (197, 'Fijian'),
            (198, 'Filipino'),
            (199, 'Finnish'),
            (200, 'Finno-Ugrian languages'),
            (201, 'Flemish'),
            (202, 'Fon'),
            (203, 'French'),
            (204, 'French - Belgium'),
            (205, 'French - Cameroon'),
            (206, 'French - Canada'),
            (207, 'French - Congo'),
            (208, 'French - Cote d\'Ivoire'),
            (209, 'French - France'),
            (210, 'French - Luxembourg'),
            (211, 'French - Mali'),
            (212, 'French - Monaco'),
            (213, 'French - Morocco'),
            (214, 'French - Senegal'),
            (215, 'French - Switzerland'),
            (216, 'French - West Indies'),
            (217, 'French, Middle (ca.1400-1600)'),
            (218, 'French, Old (842-ca.1400)'),
            (219, 'Friulian'),
            (220, 'Fulah'),
            (221, 'FYRO Macedonia'),
            (222, 'Ga'),
            (223, 'Gaelic'),
            (224, 'Gaelic - Ireland'),
            (225, 'Gaelic - Scotland'),
            (226, 'Galibi Carib'),
            (227, 'Galician'),
            (228, 'Ganda'),
            (229, 'Gayo'),
            (230, 'Gbaya'),
            (231, 'Geez'),
            (232, 'Georgian'),
            (233, 'German'),
            (234, 'German - Austria'),
            (235, 'German - Germany'),
            (236, 'German - Liechtenstein'),
            (237, 'German - Luxembourg'),
            (238, 'German - Switzerland'),
            (239, 'German, Low'),
            (240, 'German, Middle High (ca.1050-1500)'),
            (241, 'German, Old High (ca.750-1050)'),
            (242, 'Germanic languages'),
            (243, 'Gikuyu'),
            (244, 'Gilbertese'),
            (245, 'Gondi'),
            (246, 'Gorontalo'),
            (247, 'Gothic'),
            (248, 'Grebo'),
            (249, 'Greek, Ancient (to 1453)'),
            (250, 'Greek, Modern (1453-)'),
            (251, 'Greenlandic'),
            (252, 'Guarani'),
            (253, 'Gujarati'),
            (254, 'Gwich\'in'),
            (255, 'Haida'),
            (256, 'Haitian'),
            (257, 'Haitian Creole'),
            (258, 'Hausa'),
            (259, 'Hawaiian'),
            (260, 'Hebrew'),
            (261, 'Herero'),
            (262, 'Hiligaynon'),
            (263, 'Himachali languages'),
            (264, 'Hindi'),
            (265, 'Hiri Motu'),
            (266, 'Hittite'),
            (267, 'Hmong'),
            (268, 'Hungarian'),
            (269, 'Hupa'),
            (270, 'Iban'),
            (271, 'Icelandic'),
            (272, 'Ido'),
            (273, 'Igbo'),
            (274, 'Ijo languages'),
            (275, 'Iloko'),
            (276, 'Imperial Aramaic (700-300 BCE)'),
            (277, 'Inari Sami'),
            (278, 'Indic languages'),
            (279, 'Indo-European languages'),
            (280, 'Indonesian'),
            (281, 'Ingush'),
            (282, 'Interlingua (International Auxiliary Language Association)'),
            (283, 'Interlingue'),
            (284, 'Inuktitut'),
            (285, 'Inupiaq'),
            (286, 'Iranian languages'),
            (287, 'Irish'),
            (288, 'Irish, Middle (900-1200)'),
            (289, 'Irish, Old (to 900)'),
            (290, 'Iroquoian languages'),
            (291, 'Italian'),
            (292, 'Italian - Italy'),
            (293, 'Italian - Switzerland'),
            (294, 'Japanese'),
            (295, 'Javanese'),
            (296, 'Jingpho'),
            (297, 'Judeo-Arabic'),
            (298, 'Judeo-Persian'),
            (299, 'Kabardian'),
            (300, 'Kabyle'),
            (301, 'Kachin'),
            (302, 'Kalaallisut'),
            (303, 'Kalmyk'),
            (304, 'Kamba'),
            (305, 'Kannada'),
            (306, 'Kanuri'),
            (307, 'Kapampangan'),
            (308, 'Kara-Kalpak'),
            (309, 'Karachay-Balkar'),
            (310, 'Karelian'),
            (311, 'Karen languages'),
            (312, 'Kashmiri'),
            (313, 'Kashubian'),
            (314, 'Kawi'),
            (315, 'Kazakh'),
            (316, 'Khasi'),
            (317, 'Khmer'),
            (318, 'Khoisan languages'),
            (319, 'Khotanese'),
            (320, 'Kikuyu'),
            (321, 'Kimbundu'),
            (322, 'Kinyarwanda'),
            (323, 'Kirdki'),
            (324, 'Kirghiz'),
            (325, 'Kirmanjki'),
            (326, 'Klingon'),
            (327, 'Komi'),
            (328, 'Kongo'),
            (329, 'Konkani'),
            (330, 'Korean'),
            (331, 'Kosraean'),
            (332, 'Kpelle'),
            (333, 'Kru languages'),
            (334, 'Kuanyama'),
            (335, 'Kumyk'),
            (336, 'Kurdish'),
            (337, 'Kurukh'),
            (338, 'Kutenai'),
            (339, 'Kwanyama'),
            (340, 'Kyrgyz'),
            (341, 'Ladino'),
            (342, 'Lahnda'),
            (343, 'Lamba'),
            (344, 'Land Dayak languages'),
            (345, 'Lao'),
            (346, 'Latin'),
            (347, 'Latvian'),
            (348, 'Leonese'),
            (349, 'Letzeburgesch'),
            (350, 'Lezghian'),
            (351, 'Limburgan'),
            (352, 'Limburger'),
            (353, 'Limburgish'),
            (354, 'Lingala'),
            (355, 'Lithuanian'),
            (356, 'Lojban'),
            (357, 'Low German'),
            (358, 'Low Saxon'),
            (359, 'Lower Sorbian'),
            (360, 'Lozi'),
            (361, 'Luba-Katanga'),
            (362, 'Luba-Lulua'),
            (363, 'Luiseno'),
            (364, 'Lule Sami'),
            (365, 'Lunda'),
            (366, 'Luo (Kenya and Tanzania)'),
            (367, 'Lushai'),
            (368, 'Luxembourgish'),
            (369, 'Macedo-Romanian'),
            (370, 'Macedonian'),
            (371, 'Madurese'),
            (372, 'Magahi'),
            (373, 'Maithili'),
            (374, 'Makasar'),
            (375, 'Malagasy'),
            (376, 'Malay'),
            (377, 'Malay - Brunei'),
            (378, 'Malay - Malaysia'),
            (379, 'Malayalam'),
            (380, 'Maldivian'),
            (381, 'Maltese'),
            (382, 'Manchu'),
            (383, 'Mandar'),
            (384, 'Mandingo'),
            (385, 'Manipuri'),
            (386, 'Manobo languages'),
            (387, 'Manx'),
            (388, 'Maori'),
            (389, 'Mapuche'),
            (390, 'Mapudungun'),
            (391, 'Marathi'),
            (392, 'Mari'),
            (393, 'Marshallese'),
            (394, 'Marwari'),
            (395, 'Masai'),
            (396, 'Mayan languages'),
            (397, 'Mende'),
            (398, 'Mi\'kmaq'),
            (399, 'Micmac'),
            (400, 'Minangkabau'),
            (401, 'Mirandese'),
            (402, 'Mohawk'),
            (403, 'Moksha'),
            (404, 'Moldavian'),
            (405, 'Mon-Khmer languages'),
            (406, 'Mong'),
            (407, 'Mongo'),
            (408, 'Mongolian'),
            (409, 'Montenegrin'),
            (410, 'Mossi'),
            (411, 'Multiple languages'),
            (412, 'Munda languages'),
            (413, 'N\'Ko'),
            (414, 'Nahuatl languages'),
            (415, 'Nauru'),
            (416, 'Navaho'),
            (417, 'Navajo'),
            (418, 'Ndebele, North'),
            (419, 'Ndebele, South'),
            (420, 'Ndonga'),
            (421, 'Neapolitan'),
            (422, 'Nepal Bhasa'),
            (423, 'Nepali'),
            (424, 'Newari'),
            (425, 'Nias'),
            (426, 'Niger-Kordofanian languages'),
            (427, 'Nilo-Saharan languages'),
            (428, 'Niuean'),
            (429, 'No linguistic content'),
            (430, 'Nogai'),
            (431, 'Norse, Old'),
            (432, 'North American Indian languages'),
            (433, 'North Ndebele'),
            (434, 'Northern Frisian'),
            (435, 'Northern Sami'),
            (436, 'Northern Sotho'),
            (437, 'Norwegian'),
            (438, 'Norwegian - Bokml'),
            (439, 'Norwegian - Nynorsk'),
            (440, 'Not applicable'),
            (441, 'Nubian languages'),
            (442, 'Nuosu'),
            (443, 'Nyamwezi'),
            (444, 'Nyanja'),
            (445, 'Nyankole'),
            (446, 'Nynorsk, Norwegian'),
            (447, 'Nyoro'),
            (448, 'Nzima'),
            (449, 'Occidental'),
            (450, 'Occitan (post 1500)'),
            (451, 'Occitan, Old (to 1500)'),
            (452, 'Official Aramaic (700-300 BCE)'),
            (453, 'Oirat'),
            (454, 'Ojibwa'),
            (455, 'Old Bulgarian'),
            (456, 'Old Church Slavonic'),
            (457, 'Old Newari'),
            (458, 'Old Slavonic'),
            (459, 'Oriya'),
            (460, 'Oromo'),
            (461, 'Osage'),
            (462, 'Ossetian'),
            (463, 'Ossetic'),
            (464, 'Otomian languages'),
            (465, 'Pahlavi'),
            (466, 'Palauan'),
            (467, 'Pali'),
            (468, 'Pampanga'),
            (469, 'Pangasinan'),
            (470, 'Panjabi'),
            (471, 'Papiamento'),
            (472, 'Papuan languages'),
            (473, 'Pashto'),
            (474, 'Pedi'),
            (475, 'Persian'),
            (476, 'Persian, Old (ca.600-400 B.C.)'),
            (477, 'Philippine languages'),
            (478, 'Phoenician'),
            (479, 'Pilipino'),
            (480, 'Pohnpeian'),
            (481, 'Polish'),
            (482, 'Portuguese'),
            (483, 'Portuguese - Brazil'),
            (484, 'Portuguese - Portugal'),
            (485, 'Prakrit languages'),
            (486, 'Provenal, Old (to 1500)'),
            (487, 'Punjabi'),
            (488, 'Pushto'),
            (489, 'Quechua'),
            (490, 'Rajasthani'),
            (491, 'Rapanui'),
            (492, 'Rarotongan'),
            (493, 'Romance languages'),
            (494, 'Romanian'),
            (495, 'Romanian - Moldova'),
            (496, 'Romanian - Romania'),
            (497, 'Romansh'),
            (498, 'Romany'),
            (499, 'Rundi'),
            (500, 'Russian'),
            (502, 'Russian - Moldova'),
            (503, 'Sakan'),
            (504, 'Salishan languages'),
            (505, 'Samaritan Aramaic'),
            (506, 'Sami languages'),
            (507, 'Samoan'),
            (508, 'Sandawe'),
            (509, 'Sango'),
            (510, 'Sanskrit'),
            (511, 'Santali'),
            (512, 'Sardinian'),
            (513, 'Sasak'),
            (514, 'Saxon, Low'),
            (515, 'Scots'),
            (516, 'Scottish Gaelic'),
            (517, 'Selkup'),
            (518, 'Semitic languages'),
            (519, 'Sepedi'),
            (520, 'Serbian'),
            (521, 'Serbian - Cyrillic'),
            (522, 'Serbian - Latin'),
            (523, 'Serer'),
            (524, 'Shan'),
            (525, 'Shona'),
            (526, 'Sichuan Yi'),
            (527, 'Sicilian'),
            (528, 'Sidamo'),
            (529, 'Sign Languages'),
            (530, 'Siksika'),
            (531, 'Sindhi'),
            (532, 'Sinhala'),
            (533, 'Sinhalese'),
            (534, 'Sino-Tibetan languages'),
            (535, 'Siouan languages'),
            (536, 'Skolt Sami'),
            (537, 'Slave (Athapascan)'),
            (538, 'Slavic languages'),
            (539, 'Slovak'),
            (540, 'Slovenian'),
            (541, 'Sogdian'),
            (542, 'Somali'),
            (543, 'Songhai languages'),
            (544, 'Soninke'),
            (545, 'Sorbian'),
            (546, 'Sorbian languages'),
            (547, 'Sotho, Northern'),
            (548, 'Sotho, Southern'),
            (549, 'South American Indian languages'),
            (550, 'South Ndebele'),
            (551, 'Southern Altai'),
            (552, 'Southern Sami'),
            (553, 'Spanish'),
            (554, 'Spanish - Argentina'),
            (555, 'Spanish - Bolivia'),
            (556, 'Spanish - Chile'),
            (557, 'Spanish - Colombia'),
            (558, 'Spanish - Costa Rica'),
            (559, 'Spanish - Dominican Republic'),
            (560, 'Spanish - Ecuador'),
            (561, 'Spanish - El Salvador'),
            (562, 'Spanish - Guatemala'),
            (563, 'Spanish - Honduras'),
            (564, 'Spanish - Mexico'),
            (565, 'Spanish - Nicaragua'),
            (566, 'Spanish - Panama'),
            (567, 'Spanish - Paraguay'),
            (568, 'Spanish - Peru'),
            (569, 'Spanish - Puerto Rico'),
            (570, 'Spanish - Spain (Traditional)'),
            (571, 'Spanish - Uruguay'),
            (572, 'Spanish - Venezuela'),
            (573, 'Sranan Tongo'),
            (574, 'Standard Moroccan Tamazight'),
            (575, 'Sukuma'),
            (576, 'Sumerian'),
            (577, 'Sundanese'),
            (578, 'Susu'),
            (579, 'Swahili'),
            (580, 'Swati'),
            (581, 'Swedish'),
            (582, 'Swedish - Finland'),
            (583, 'Swedish - Sweden'),
            (584, 'Swiss German'),
            (585, 'Syriac'),
            (586, 'Tagalog'),
            (587, 'Tahitian'),
            (588, 'Tai languages'),
            (589, 'Tajik'),
            (590, 'Tamashek'),
            (591, 'Tamil'),
            (592, 'Tatar'),
            (593, 'Telugu'),
            (594, 'Tereno'),
            (595, 'Tetum'),
            (596, 'Thai'),
            (597, 'Tibetan'),
            (598, 'Tigre'),
            (599, 'Tigrinya'),
            (600, 'Timne'),
            (601, 'Tiv'),
            (602, 'tlhIngan-Hol'),
            (603, 'Tlingit'),
            (604, 'Tok Pisin'),
            (605, 'Tokelau'),
            (606, 'Tonga (Nyasa)'),
            (607, 'Tonga (Tonga Islands)'),
            (608, 'Tsimshian'),
            (609, 'Tsonga'),
            (610, 'Tswana'),
            (611, 'Tumbuka'),
            (612, 'Tupi languages'),
            (613, 'Turkish'),
            (614, 'Turkish, Ottoman (1500-1928)'),
            (615, 'Turkmen'),
            (616, 'Tuvalu'),
            (617, 'Tuvinian'),
            (618, 'Twi'),
            (619, 'Udmurt'),
            (620, 'Ugaritic'),
            (621, 'Uighur'),
            (622, 'Ukrainian'),
            (623, 'Umbundu'),
            (624, 'Uncoded languages'),
            (625, 'Undetermined'),
            (626, 'Upper Sorbian'),
            (627, 'Urdu'),
            (628, 'Uyghur'),
            (629, 'Uzbek'),
            (630, 'Uzbek - Cyrillic'),
            (631, 'Uzbek - Latin'),
            (632, 'Vai'),
            (633, 'Valencian'),
            (634, 'Venda'),
            (635, 'Vietnamese'),
            (636, 'Volapük'),
            (637, 'Votic'),
            (638, 'Wakashan languages'),
            (639, 'Walloon'),
            (640, 'Waray'),
            (641, 'Washo'),
            (642, 'Welsh'),
            (643, 'Western Frisian'),
            (644, 'Western Pahari languages'),
            (645, 'Wolaitta'),
            (646, 'Wo+A649laytta'),
            (647, 'Wolof'),
            (648, 'Xhosa'),
            (649, 'Yakut'),
            (650, 'Yao'),
            (651, 'Yapese'),
            (652, 'Yiddish'),
            (653, 'Yoruba'),
            (654, 'Yupik languages'),
            (655, 'Zande languages'),
            (656, 'Zapotec'),
            (657, 'Zaza'),
            (658, 'Zazaki'),
            (659, 'Zenaga'),
            (660, 'Zhuang'),
            (661, 'Zulu'),
            (662, 'Zuni');");

        DB::commit();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('languages');
    }
};
